### ISSUE TITLE
vue-tour compatible with es2015 transpilation

### ISSUE THREAD

**Issue by balmeidaa** [pulsardev/vue-tour#61]
I redacted [this issue in stackoverflow](https://stackoverflow.com/questions/53657528/vuejs-module-build-failed-error-couldnt-find-preset-vue-app-relative-to-di),
i have a problem with my project .babelrc es2015 transpilation, if i import the vue-tour as is, i get this erro message:

```
error  in ./~/vue-tour/dist/vue-tour.umd.js

Module build failed: Error: Couldn't find preset "@vue/app" relative to directory "C:\\xampp\\htdocs\\avanttia\\node_modules\\vue-tour"
    at C:\xampp\htdocs\avanttia\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\xampp\htdocs\avanttia\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\xampp\htdocs\avanttia\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\xampp\htdocs\avanttia\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\xampp\htdocs\avanttia\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\xampp\htdocs\avanttia\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\xampp\htdocs\avanttia\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\xampp\htdocs\avanttia\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\xampp\htdocs\avanttia\node_modules\babel-loader\lib\index.js:46:20)
    at Object.module.exports (C:\xampp\htdocs\avanttia\node_modules\babel-loader\lib\index.js:163:20)

 @ ./resources/assets/js/wizard/main.js 49:15-34
 @ multi ./resources/assets/js/wizard/main.js
```

If in the node_modules/vue-tour library i change the .babelrc file to this:
```
"presets": [
        "es2015"
      ]
```

it works as expected with no compilation errors. please can you fix this.

**Comment by NigmaX** [comment]
I have the same issue.
working outside of vue CLI environment will case this error.
please fix it.
thanks.

**Comment by crow7m** [comment]
Same here, please let us know what can be done to solve this.
Thank you

**Comment by balmeidaa** [comment]
[I found a solution for this](https://stackoverflow.com/a/54101496/2796268), not sure if might help you but it's work to check it out.

**Comment by wwardaww** [comment]
Same issue
