### ISSUE TITLE
Error: Couldn't find preset "@vue/app"

### ISSUE THREAD

**Issue by artes07** [pulsardev/vue-tour#91]
how can i fix this error?

"myPath" this is the path to the project

 ERROR in ./node_modules/vue-tour/dist/vue-tour.umd.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Couldn't find preset "@vue/app" relative to directory "myPath\\node_modules\\vue-tour"
        at myPath\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
        at Array.map (<anonymous>)
        at OptionManager.resolvePresets (myPath\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
        at OptionManager.mergePresets (myPath\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
        at OptionManager.mergeOptions (myPath\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
        at OptionManager.init (myPath\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
        at File.initOptions (myPath\node_modules\babel-core\lib\transformation\file\index.js:212:65)
        at new File (myPath\node_modules\babel-core\lib\transformation\file\index.js:135:24)
        at Pipeline.transform (myPath\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
        at transpile (myPath\node_modules\babel-loader\lib\index.js:50:20)
        at Object.module.exports (myPath\node_modules\babel-loader\lib\index.js:173:20)

**Comment by Outpox** [comment]
Hey there. Please provide more information, this is not enough for us to help you. How are you including the library in your project?

**Comment by artes07** [comment]
I just followed the instructions in the Getting Started section and nothing more

**Comment by HZooly** [comment]
Hi @artes07, as you can see on this CodeSandbox, there is nothing wrong with example provided in Getting Started. 

https://codesandbox.io/s/vue-template-z1pq9?fontsize=14

**Comment by artes07** [comment]
I installed babel-preset-vue-app, added "presets": ["vue-app"] to the .babelrc file and added exclude: /node_modules/ after loader: 'babel-loader' in webpack.config.js. this solved my problem.
